### PR TITLE
add headers key/value read from the message to the generated logstash event

### PR DESCRIPTION
**Pull request by yanayita**
Solves #38

### CODE REVIEW

**Comment by Zico56** [comment]
Hello there,

Is there a release scheduled for this development ?

I actually need to parse headers from kafka message in logstash.
I tested this development with a custom compile of the plugin, it seems to work pretty well.

However, if testing a custom plugin is possible on our dev environement,
for production purpose, I'll prefer to have this in an official release.

Thanks.

**Comment by yanayita** [comment]
Hi Zico, I didn't have time to progress on this. The problem is that CI checks have failed, because in order to implement testing for the headers, we cannot use kafka-console-producer, and instead I relied on using kafcat which allows generating messages with headers for the tests, but cannot use kafcat (using docker) with the current CI setup.

Maybe someone else could advise a workaround? 
Otherwise for now, I could simply remove the tests for this implementation so that CI can complete

**Comment by andsel** [comment]
Hi @yanayita thank you for contributing with this PR. I think we are almost there, but it only needs to address a couple of things:

- instead to introduce another flag (name it `decorate_headers`) I would go with Ry suggestion to have a tri-state `decorate_events`
-  add some testing (unit or integration) to prove the fix
-  the decode phase should be in UTF-8, `header.value.to_s` convert in UTF-8 but it could raise error (this has to be verified) if the value is not a valid UTF-8 string, while in issue #38 was asked to skip in case of parsing error of the single header

**Comment by andsel** [comment]
I close and reopen to see if the webhook to Travis.com is updated

**Pull request closed without merging**
